---

  # This GitHub Actions workflow can be triggered in two ways:
  # 1. Automatically on push to any branch (runs in dry-run mode for safety)
  # 2. Manually via workflow_dispatch with configurable parameters
  #
  # The workflow delegates the actual NPM publishing process to the re-npm-publish.yml workflow
  # from the qubership-workflow-hub repository, which performs the following tasks:
  # 1. Checks out the repository.
  # 2. Sets up Node.js environment.
  # 3. Installs dependencies.
  # 4. Detects if the project is a Lerna monorepo.
  # 5. Updates dependencies if required.
  # 6. Updates package version in package.json or lerna.json.
  # 7. Builds the project.
  # 8. Runs tests.
  # 9. Commits and pushes changes.
  # 10. Publishes the package to NPM registry.
  
  # To make it work for your project, you need to adjust the package.json and add configuration file for GitHub release.
  # Please find detailed instructions:
  # https://github.com/netcracker/qubership-workflow-hub?tab=readme-ov-file#npm-project-release-workflow
  #
  # Note: When triggered by push, the workflow automatically runs in dry-run mode to prevent
  # accidental publishing. Use workflow_dispatch for actual releases.
  
  name: Publish NPM package
  
  run-name: Publish NPM package${{ github.event_name == 'workflow_dispatch' && inputs.version && format(' {0}', inputs.version) || '' }}${{ (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.dry-run)) && ' Test' || '' }}
  
  on:
    push:
      branches:
        - '**'
    workflow_dispatch:
      inputs:
        version:
          description: 'Release version for NPM (e.g., 1.0.0)'
          required: false
          type: string
        scope:
          description: 'NPM scope for the package'
          required: false
          type: string
          default: '@netcracker'
        node-version:
          required: false
          type: string
          default: "22.x"
        registry-url:
          required: false
          type: string
          default: "https://npm.pkg.github.com"
        update-nc-dependency:
          required: false
          type: boolean
          default: false
        dry-run:
          description: 'Run in dry-run mode (no actual publishing)'
          required: false
          type: boolean
          default: false
        npm-dist-tag:
          description: 'NPM distribution tag'
          required: false
          type: string
          default: 'latest'
        branch_name:
          required: false
          type: string
          default: "main"
  
  permissions:
    contents: write
    packages: write
  
  jobs:
    npm-publish:
      uses: Netcracker/qubership-workflow-hub/.github/workflows/re-npm-publish.yml@bugfix/update_npm
      with:
        version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
        scope: ${{ github.event_name == 'workflow_dispatch' && inputs.scope || '@netcracker' }}
        node-version: ${{ github.event_name == 'workflow_dispatch' && inputs.node-version || '22.x' }}
        registry-url: ${{ github.event_name == 'workflow_dispatch' && inputs.registry-url || 'https://npm.pkg.github.com' }}
        update-nc-dependency: ${{ github.event_name == 'workflow_dispatch' && inputs.update-nc-dependency || false }}
        dry-run: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.dry-run) }}
        dist-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.npm-dist-tag || 'latest' }}
        branch_name: ${{ github.event_name == 'workflow_dispatch' && inputs.branch_name || github.ref_name }}
      secrets: inherit